/**
 * Database Cleanup Script: clean-ai-disclaimers.ts
 *
 * Removes AI disclaimer text from ONLY scraped / auto-generated articles in the database.
 *
 * Run via: npx tsx src/scripts/clean-ai-disclaimers.ts
 */

import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { cleanArticleContent } from "../lib/scraper/clean-content";

const prisma = new PrismaClient();

async function main() {
  console.log("Memulai pembersihan klausa AI KHUSUS pada artikel hasil scrape (isAutoGenerated: true)...");

  const articles = await prisma.article.findMany({
    where: {
      isAutoGenerated: true,
    },
    select: { id: true, slug: true, title: true, content: true },
  });

  console.log(`Ditemukan ${articles.length} artikel hasil scrape yang perlu diperiksa.`);

  let updatedCount = 0;
  for (const article of articles) {
    if (!article.content) continue;
    const cleaned = cleanArticleContent(article.content);
    if (cleaned !== article.content) {
      await prisma.article.update({
        where: { id: article.id },
        data: { content: cleaned },
      });
      updatedCount++;
      console.log(`[FIXED] Artikel: ${article.slug}`);
    }
  }

  console.log(`\nSelesai! Berhasil memperbarui ${updatedCount} dari ${articles.length} artikel.`);
}

main()
  .catch((err) => {
    console.error("Error saat membersihkan database:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
