/**
 * Database Cleanup Script: clean-ai-disclaimers.ts
 *
 * Removes AI disclaimer text and embedded body images from all existing articles in the database.
 *
 * Run via: npx tsx src/scripts/clean-ai-disclaimers.ts
 */

import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { cleanArticleContent } from "../lib/scraper/clean-content";

const prisma = new PrismaClient();

async function main() {
  console.log("Memulai pembersihan klausa AI dan foto body di database...");

  const articles = await prisma.article.findMany({
    where: {
      OR: [
        { isAutoGenerated: true },
        { content: { contains: "dukungan AI" } },
        { content: { contains: "ditulis ulang oleh tim editorial" } },
        { content: { contains: "dibuat oleh AI" } },
        { content: { contains: "Versi Kartawarta ditulis ulang" } },
        { content: { contains: "<figure" } },
        { content: { contains: "<img" } },
      ],
    },
    select: { id: true, slug: true, title: true, content: true },
  });

  console.log(`Ditemukan ${articles.length} artikel yang perlu diperiksa.`);

  let updatedCount = 0;
  for (const article of articles) {
    if (!article.content) continue;
    const cleaned = cleanArticleContent(article.content);
    if (cleaned !== article.content) {
      await prisma.article.update({
        where: { id: article.id },
        data: { content: cleaned },
      });
      updatedCount++;
      console.log(`[FIXED] Artikel: ${article.slug}`);
    }
  }

  console.log(`\nSelesai! Berhasil memperbarui ${updatedCount} dari ${articles.length} artikel.`);
}

main()
  .catch((err) => {
    console.error("Error saat membersihkan database:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
