/**
 * Database Maintenance Script: clean-scraped-articles.ts
 *
 * Cleans ONLY scraped / auto-generated articles (isAutoGenerated: true) in the database according to current editorial rules:
 *   1. Removes AI disclaimer phrases (e.g. "Versi Kartawarta ditulis ulang oleh tim editorial dengan dukungan AI...")
 *   2. Removes embedded body images (<figure>, <img>, <picture>) from the article content body,
 *      so only the main featured image (featuredImage) is used for the article.
 *   3. Cleans leftover empty paragraphs or broken tags.
 *
 * Manual articles (isAutoGenerated: false/null) are strictly UNTOUCHED.
 *
 * Usage:
 *   npx tsx src/scripts/clean-scraped-articles.ts
 */

import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { cleanArticleContent } from "../lib/scraper/clean-content";

const prisma = new PrismaClient();

async function main() {
  console.log("Memulai pembersihan KHUSUS artikel hasil scrape (isAutoGenerated: true)...");

  // ONLY select articles that were auto-generated / scraped!
  const articles = await prisma.article.findMany({
    where: {
      isAutoGenerated: true,
    },
    select: {
      id: true,
      title: true,
      slug: true,
      content: true,
      isAutoGenerated: true,
      featuredImage: true,
    },
  });

  console.log(`Ditemukan ${articles.length} artikel hasil scrape yang perlu diperiksa.`);

  let updatedCount = 0;
  for (const article of articles) {
    if (!article.content) continue;
    const cleaned = cleanArticleContent(article.content);
    if (cleaned !== article.content) {
      await prisma.article.update({
        where: { id: article.id },
        data: { content: cleaned },
      });
      updatedCount++;
      console.log(`[FIXED SCRAPED] ${article.title} (${article.slug})`);
    }
  }

  console.log(`\nSelesai! Berhasil merapikan ${updatedCount} dari ${articles.length} artikel hasil scrape.`);
}

main()
  .catch((err) => {
    console.error("Gagal menjalankan script pembersihan:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
