/**
 * Maintenance Script: restore-manual-articles.ts
 *
 * Checks if revisions exist in the `Revision` table for manual articles (isAutoGenerated: false),
 * and restores the latest revision prior to the cleanup script execution.
 */

import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Memeriksa revisi untuk mengembalikan artikel manual (isAutoGenerated: false)...");

  // Find manual articles
  const manualArticles = await prisma.article.findMany({
    where: {
      isAutoGenerated: false,
    },
    select: {
      id: true,
      title: true,
      slug: true,
      content: true,
      updatedAt: true,
      revisions: {
        orderBy: { createdAt: "desc" },
        take: 5,
      },
    },
  });

  console.log(`Total artikel manual: ${manualArticles.length}`);

  let restoredCount = 0;
  for (const article of manualArticles) {
    if (article.revisions && article.revisions.length > 0) {
      // Latest revision before current content
      const prevRevision = article.revisions[0];
      if (prevRevision.content && prevRevision.content !== article.content) {
        await prisma.article.update({
          where: { id: article.id },
          data: {
            content: prevRevision.content,
            title: prevRevision.title || article.title,
          },
        });
        restoredCount++;
        console.log(`[RESTORED VIA REVISION] ${article.title} (${article.slug})`);
      }
    }
  }

  console.log(`\nSelesai! Berhasil mengembalikan ${restoredCount} artikel manual dari riwayat revisi.`);
}

main()
  .catch((err) => {
    console.error("Gagal mengembalikan artikel:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
