/**
 * POST /api/admin/clean-scraped-articles
 *
 * Batch-fixes existing articles in the database to comply with current editorial rules:
 *   1. Removes AI disclaimer text phrases (e.g. "Versi Kartawarta ditulis ulang oleh tim editorial dengan dukungan AI...")
 *   2. Removes body images (<figure>, <img>) from article content HTML.
 *
 * Auth: SUPER_ADMIN / CHIEF_EDITOR
 */

import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireRole, successResponse, errorResponse, logAudit } from "@/lib/api-utils";
import { cleanArticleContent } from "@/lib/scraper/clean-content";
import { Role } from "@prisma/client";

export const dynamic = "force-dynamic";
export const maxDuration = 180;

export async function POST(req: NextRequest) {
  try {
    const session = await requireRole([Role.SUPER_ADMIN, Role.CHIEF_EDITOR]);
    const raw = await req.json().catch(() => ({}));
    const apply = raw?.apply === true;

    const articles = await prisma.article.findMany({
      where: {
        OR: [
          { isAutoGenerated: true },
          { content: { contains: "dukungan AI" } },
          { content: { contains: "<figure" } },
          { content: { contains: "<img" } },
        ],
      },
      select: {
        id: true,
        title: true,
        slug: true,
        content: true,
        isAutoGenerated: true,
      },
    });

    if (!apply) {
      let needsFixCount = 0;
      const samples: { title: string; slug: string }[] = [];
      for (const article of articles) {
        if (!article.content) continue;
        const cleaned = cleanArticleContent(article.content);
        if (cleaned !== article.content) {
          needsFixCount++;
          if (samples.length < 5) samples.push({ title: article.title, slug: article.slug });
        }
      }

      return successResponse({
        scanned: articles.length,
        needsFixCount,
        samples,
      });
    }

    let fixedCount = 0;
    for (const article of articles) {
      if (!article.content) continue;
      const cleaned = cleanArticleContent(article.content);
      if (cleaned !== article.content) {
        await prisma.article.update({
          where: { id: article.id },
          data: { content: cleaned },
        });
        fixedCount++;
      }
    }

    await logAudit(
      session.user.id,
      "CLEAN_SCRAPED_ARTICLES",
      "article",
      "batch",
      JSON.stringify({ scanned: articles.length, fixedCount }),
    );

    return successResponse({
      scanned: articles.length,
      fixed: fixedCount,
    });
  } catch (err) {
    return errorResponse(err);
  }
}
