/**
 * POST /api/admin/auto-article/trigger
 *
 * Dedicated Admin trigger endpoint: Generates 1-3 auto-article drafts using Qwen / callAI
 * for active TargetKeywords.
 * Protected by SUPER_ADMIN session auth.
 */

import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { slugify } from "@/lib/utils";
import { sanitizeHtml } from "@/lib/sanitize";
import { cleanArticleContent } from "@/lib/scraper/clean-content";
import { requireRole, successResponse, errorResponse, logAudit } from "@/lib/api-utils";
import { extractFirstImageUrl } from "@/lib/image-extract";
import { callAI } from "@/lib/ai-client";
import { onArticlePublished } from "@/lib/seo-auto";
import { Role } from "@prisma/client";

export const dynamic = "force-dynamic";
export const maxDuration = 180;

async function uniqueSlug(base: string): Promise<string> {
  const root = slugify(base).slice(0, 90) || "artikel";
  const existing = await prisma.article.findUnique({
    where: { slug: root },
    select: { id: true },
  });
  if (!existing) return root;
  const suffix = Math.random().toString(36).slice(2, 8);
  return `${root}-${suffix}`;
}

export async function POST(req: NextRequest) {
  try {
    const session = await requireRole([Role.SUPER_ADMIN]);

    // Check Auto Publish setting
    const autoPublishRow = await prisma.systemSetting.findUnique({
      where: { key: "auto_article_auto_publish" },
    });
    const isAutoPublish = autoPublishRow?.value === "true";
    const status = isAutoPublish ? "PUBLISHED" : "DRAFT";
    const publishedAt = isAutoPublish ? new Date() : null;
    const verificationLabel = isAutoPublish ? "VERIFIED" : "UNVERIFIED";

    // Pick active keyword (random from top 10 by priority)
    const keywords = await prisma.targetKeyword.findMany({
      where: { isActive: true },
      orderBy: { priority: "desc" },
      take: 10,
    });

    if (keywords.length === 0) {
      return successResponse({ created: 0, reason: "tidak ada keyword aktif" });
    }

    const kw = keywords[Math.floor(Math.random() * keywords.length)];

    const userPrompt = `Anda jurnalis senior Kartawarta (media berita digital Bandung dengan fokus bisnis, ekonomi, pemerintahan, dan hukum, plus topik general lain).
Tulis sebuah artikel berita lengkap yang fresh, faktual, informatif, dan SEO-friendly tentang topik: "${kw.keyword}".

ATURAN WAJIB:
- Lead paragraf wajib menjawab 5W+1H.
- Hasil HTML rapi: <p>, <h2>, <ul>, <strong> seperlunya.
- DILARANG KERAS menyertakan tag gambar (<img>), foto tambahan, atau klausa/disclaimer AI di dalam isi artikel.

Format output WAJIB JSON valid (tanpa teks lain di luar JSON):
{
  "title": "judul Kartawarta fresh & menarik (50-80 karakter)",
  "excerpt": "ringkasan 130-160 karakter",
  "content": "body artikel HTML 500-800 kata, lead 5W+1H, paragraf rapi",
  "suggestedTags": ["tag1", "tag2", "tag3"]
}`;

    let aiRes;
    try {
      // Primary: Qwen (qwen-plus) AI
      aiRes = await callAI({
        feature: "article_draft",
        userPrompt,
        maxTokens: 2500,
        temperature: 0.65,
        forceProvider: "qwen",
      });
    } catch {
      // Fallback: general callAI (Claude / DeepSeek)
      aiRes = await callAI({
        feature: "article_draft",
        userPrompt,
        maxTokens: 2500,
        temperature: 0.65,
      });
    }

    const jsonStr = aiRes.text.trim().match(/\{[\s\S]*\}/)?.[0] || aiRes.text;
    let parsed;
    try {
      parsed = JSON.parse(jsonStr);
    } catch {
      throw new Error("AI did not return valid JSON output");
    }

    if (!parsed || typeof parsed.title !== "string" || typeof parsed.content !== "string") {
      throw new Error("AI output structure is invalid");
    }

    // Resolve category
    let categoryId = kw.categoryId;
    if (!categoryId) {
      const firstCat = await prisma.category.findFirst({
        orderBy: { order: "asc" },
        select: { id: true },
      });
      categoryId = firstCat?.id ?? null;
    }
    if (!categoryId) {
      throw new Error("Tidak ada kategori yang tersedia di database");
    }

    // Clean content HTML
    const bodyHtml = cleanArticleContent(sanitizeHtml(parsed.content));
    const featuredImage = extractFirstImageUrl(parsed.content) || null;
    const slug = await uniqueSlug(parsed.title);

    const article = await prisma.article.create({
      data: {
        title: parsed.title.slice(0, 250),
        slug,
        content: bodyHtml,
        excerpt: (parsed.excerpt || "").slice(0, 500) || null,
        seoTitle: parsed.title.slice(0, 60),
        seoDescription: (parsed.excerpt || "").slice(0, 160),
        featuredImage,
        status,
        publishedAt,
        verificationLabel,
        isAutoGenerated: true,
        sourceArticleId: null,
        authorId: session.user.id,
        categoryId,
      },
      select: { id: true, slug: true, title: true, status: true },
    });

    // Tags
    if (Array.isArray(parsed.suggestedTags) && parsed.suggestedTags.length > 0) {
      const tagsToConnect = parsed.suggestedTags
        .filter((t: unknown): t is string => typeof t === "string" && t.trim().length > 0)
        .map((t: string) => ({ name: t.trim(), slug: slugify(t.trim()) }));

      if (tagsToConnect.length > 0) {
        await prisma.article
          .update({
            where: { id: article.id },
            data: {
              tags: {
                connectOrCreate: tagsToConnect.map((t: { name: string; slug: string }) => ({
                  where: { slug: t.slug },
                  create: { name: t.name, slug: t.slug },
                })),
              },
            },
          })
          .catch(() => {});
      }
    }

    // Trigger SEO / Social / Cache indexing if auto-published
    if (isAutoPublish) {
      await onArticlePublished(article.slug, article.id).catch(() => {});
    }

    // Update keyword lastGeneratedAt
    await prisma.targetKeyword
      .update({
        where: { id: kw.id },
        data: { lastGeneratedAt: new Date() },
      })
      .catch(() => {});

    await logAudit(
      session.user.id,
      "ADMIN_TRIGGER_AUTO_ARTICLE",
      "article",
      article.id,
      JSON.stringify({ keyword: kw.keyword, provider: aiRes.provider, status: article.status }),
    );

    return successResponse({
      created: 1,
      article: {
        id: article.id,
        slug: article.slug,
        title: article.title,
        status: article.status,
        keyword: kw.keyword,
        provider: aiRes.provider,
      },
    });
  } catch (err) {
    return errorResponse(err);
  }
}
